
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BanqueService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8989/BanqueService?wsdl")
public class BanqueService_Service
    extends Service
{

    private final static URL BANQUESERVICE_WSDL_LOCATION;
    private final static WebServiceException BANQUESERVICE_EXCEPTION;
    private final static QName BANQUESERVICE_QNAME = new QName("http://ws/", "BanqueService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/BanqueService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANQUESERVICE_WSDL_LOCATION = url;
        BANQUESERVICE_EXCEPTION = e;
    }

    public BanqueService_Service() {
        super(__getWsdlLocation(), BANQUESERVICE_QNAME);
    }

    public BanqueService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANQUESERVICE_QNAME, features);
    }

    public BanqueService_Service(URL wsdlLocation) {
        super(wsdlLocation, BANQUESERVICE_QNAME);
    }

    public BanqueService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANQUESERVICE_QNAME, features);
    }

    public BanqueService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanqueService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort() {
        return super.getPort(new QName("http://ws/", "BanqueServicePort"), BanqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BanqueServicePort"), BanqueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANQUESERVICE_EXCEPTION!= null) {
            throw BANQUESERVICE_EXCEPTION;
        }
        return BANQUESERVICE_WSDL_LOCATION;
    }

}
